"""Add missing models and update incomplete models

Revision ID: 016db90c80a2
Revises: 10362aa0cba9
Create Date: 2026-02-03 23:55:23.855679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016db90c80a2'
down_revision: Union[str, None] = '10362aa0cba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_availability',
    sa.Column('equipment', sa.String(length=50), nullable=True),
    sa.Column('equipment_name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_schedule',
    sa.Column('schedule_name', sa.String(length=255), nullable=True),
    sa.Column('equipment_group', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['equipment_group'], ['equipment_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_availability_details',
    sa.Column('equipment_availability', sa.String(length=50), nullable=True),
    sa.Column('hour', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_availability'], ['equipment_availability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_schedule_details',
    sa.Column('equipment_schedule', sa.String(length=50), nullable=True),
    sa.Column('day', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('is_operating', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_schedule'], ['equipment_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('asset', 'asset_tag',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('inventory', sa.Column('workflow_state', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('transaction_type', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('inventory', sa.Column('assigned_to', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('serial_number', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('financial_asset_number', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('site', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('store_location', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('zone', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('bin_location', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('item', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('item_type', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('item_name', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('asset_tag', sa.String(length=255), nullable=True))
    op.add_column('inventory', sa.Column('unit_of_measure', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('asset', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('base_unit_cost', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('actual_inv', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('available_inv', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('reserved_inv', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('freeze', sa.Boolean(), nullable=True))
    op.add_column('inventory', sa.Column('warn', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'unit_of_measure', ['unit_of_measure'], ['id'])
    op.create_foreign_key(None, 'inventory', 'site', ['site'], ['id'])
    op.create_foreign_key(None, 'inventory', 'zone', ['zone'], ['id'])
    op.create_foreign_key(None, 'inventory', 'item', ['item'], ['id'])
    op.create_foreign_key(None, 'inventory', 'employee', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'inventory', 'bin', ['bin_location'], ['id'])
    op.create_foreign_key(None, 'inventory', 'store', ['store_location'], ['id'])
    op.create_foreign_key(None, 'inventory', 'workflow_states', ['workflow_state'], ['id'])
    op.create_foreign_key(None, 'inventory', 'location', ['location'], ['id'])
    op.create_foreign_key(None, 'inventory', 'asset', ['asset'], ['id'])
    op.drop_column('inventory', 'name')
    op.drop_column('inventory', 'description')
    op.add_column('item', sa.Column('item_name', sa.String(length=255), nullable=True))
    op.add_column('item', sa.Column('item_class', sa.String(length=50), nullable=True))
    op.add_column('item', sa.Column('item_type', sa.String(length=255), nullable=True))
    op.add_column('item', sa.Column('abc_code', sa.String(length=255), nullable=True))
    op.add_column('item', sa.Column('item_img', sa.String(length=500), nullable=True))
    op.add_column('item', sa.Column('expense_account', sa.String(length=50), nullable=True))
    op.add_column('item', sa.Column('inventory_adjustment_account', sa.String(length=50), nullable=True))
    op.add_column('item', sa.Column('primary_vendor', sa.String(length=50), nullable=True))
    op.add_column('item', sa.Column('asset_class', sa.String(length=50), nullable=True))
    op.add_column('item', sa.Column('uom', sa.String(length=50), nullable=True))
    op.add_column('item', sa.Column('actual_qty_on_hand', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('available_capacity', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('unit_cost', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('reserved_capacity', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('is_serialized', sa.Boolean(), nullable=True))
    op.add_column('item', sa.Column('inspection_required', sa.Boolean(), nullable=True))
    op.add_column('item', sa.Column('is_equipment', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'item', 'account', ['inventory_adjustment_account'], ['id'])
    op.create_foreign_key(None, 'item', 'asset_class', ['asset_class'], ['id'])
    op.create_foreign_key(None, 'item', 'account', ['expense_account'], ['id'])
    op.create_foreign_key(None, 'item', 'unit_of_measure', ['uom'], ['id'])
    op.create_foreign_key(None, 'item', 'item_class', ['item_class'], ['id'])
    op.create_foreign_key(None, 'item', 'vendor', ['primary_vendor'], ['id'])
    op.drop_column('item', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'is_equipment')
    op.drop_column('item', 'inspection_required')
    op.drop_column('item', 'is_serialized')
    op.drop_column('item', 'reserved_capacity')
    op.drop_column('item', 'unit_cost')
    op.drop_column('item', 'available_capacity')
    op.drop_column('item', 'actual_qty_on_hand')
    op.drop_column('item', 'uom')
    op.drop_column('item', 'asset_class')
    op.drop_column('item', 'primary_vendor')
    op.drop_column('item', 'inventory_adjustment_account')
    op.drop_column('item', 'expense_account')
    op.drop_column('item', 'item_img')
    op.drop_column('item', 'abc_code')
    op.drop_column('item', 'item_type')
    op.drop_column('item', 'item_class')
    op.drop_column('item', 'item_name')
    op.add_column('inventory', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'warn')
    op.drop_column('inventory', 'freeze')
    op.drop_column('inventory', 'reserved_inv')
    op.drop_column('inventory', 'available_inv')
    op.drop_column('inventory', 'actual_inv')
    op.drop_column('inventory', 'base_unit_cost')
    op.drop_column('inventory', 'asset')
    op.drop_column('inventory', 'unit_of_measure')
    op.drop_column('inventory', 'asset_tag')
    op.drop_column('inventory', 'item_name')
    op.drop_column('inventory', 'item_type')
    op.drop_column('inventory', 'item')
    op.drop_column('inventory', 'bin_location')
    op.drop_column('inventory', 'zone')
    op.drop_column('inventory', 'store_location')
    op.drop_column('inventory', 'location_name')
    op.drop_column('inventory', 'location')
    op.drop_column('inventory', 'site')
    op.drop_column('inventory', 'financial_asset_number')
    op.drop_column('inventory', 'serial_number')
    op.drop_column('inventory', 'assigned_to')
    op.drop_column('inventory', 'date')
    op.drop_column('inventory', 'transaction_type')
    op.drop_column('inventory', 'workflow_state')
    op.alter_column('asset', 'asset_tag',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('equipment_schedule_details')
    op.drop_table('equipment_availability_details')
    op.drop_table('equipment_schedule')
    op.drop_table('equipment_availability')
    # ### end Alembic commands ###
