"""Fix model field types and constraints

Revision ID: 10362aa0cba9
Revises: 6e84b7cad9d1
Create Date: 2026-02-02 18:03:31.352104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10362aa0cba9'
down_revision: Union[str, None] = '6e84b7cad9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_comment')
    op.drop_table('todo')
    op.drop_table('project')
    op.alter_column('account', 'account_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('account', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('asset', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('asset', 'asset_tag',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'asset', 'site', ['site'], ['id'])
    op.create_foreign_key(None, 'asset', 'manufacturer', ['manufacturer'], ['id'])
    op.create_foreign_key(None, 'asset', 'employee', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'asset', 'model', ['model'], ['id'])
    op.create_foreign_key(None, 'asset', 'department', ['department'], ['id'])
    op.drop_column('asset', 'asset_class_name')
    op.drop_column('asset', 'manufacturer_name')
    op.alter_column('asset_class', 'class_icon',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('asset_class_property', 'uom_short_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('asset_property', 'uom_short_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('breakdown', 'start_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('breakdown', 'end_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('checklist', 'checklist_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('cost_code', 'code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('cost_code', 'scope',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_foreign_key(None, 'cost_code', 'site', ['site'], ['id'])
    op.alter_column('currency', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('department', 'department_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('department', 'overhead_method',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('disposed', 'condition',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('disposed', 'disposal_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('disposed', 'disposal_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_foreign_key(None, 'disposed', 'site', ['site'], ['id'])
    op.create_foreign_key(None, 'employee_site', 'department', ['department'], ['id'])
    op.create_foreign_key(None, 'employee_site', 'site', ['site'], ['id'])
    op.create_foreign_key(None, 'employee_site', 'employee', ['employee'], ['id'])
    op.alter_column('entity_permissions', 'can_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('entity_permissions', 'can_create',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('entity_permissions', 'can_update',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('entity_permissions', 'can_delete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('entity_permissions', 'in_sidebar',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('equipment', 'equipment_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('equipment', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'equipment', 'employee', ['custodian'], ['id'])
    op.create_foreign_key(None, 'equipment', 'site', ['site'], ['id'])
    op.alter_column('incident', 'severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_foreign_key(None, 'incident', 'site', ['site'], ['id'])
    op.create_foreign_key(None, 'incident', 'department', ['department'], ['id'])
    op.create_foreign_key(None, 'incident', 'employee', ['assigned_to'], ['id'])
    op.alter_column('incident_employee', 'role_in_incident',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('incident_employee', 'injury_severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_foreign_key(None, 'incident_employee', 'employee', ['employee'], ['id'])
    op.alter_column('inventory_adjustment', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('inventory_adjustment', 'reference_doctype',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('item_class', 'item_class_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('item_class', 'valuation_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('item_issue', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('item_issue', 'issue_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('item_return', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('item_return', 'return_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('labor', 'labor_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('labor', 'pr_line_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'labor', 'employee', ['employee'], ['id'])
    op.alter_column('labor_availability_details', 'hour',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('labor_availability_details', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('location', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'location', 'site', ['site'], ['id'])
    op.alter_column('maintenance_calendar', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('maintenance_condition', 'uom_short_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('maintenance_condition', 'property_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('maintenance_condition', 'comparison_operator',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('maintenance_order_detail', 'due_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('maintenance_order_detail', 'resource_availability_status',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('maintenance_request', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('maintenance_request', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('organization', 'organizational_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('planned_maintenance_activity', 'maintenance_schedule',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('position', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('position', 'attach_img',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'position', 'site', ['site'], ['id'])
    op.alter_column('position_relation', 'position_a_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('position_relation', 'position_b_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('purchase_request', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('purchase_request_line', sa.Column('workflow_state', sa.String(length=255), nullable=True))
    op.add_column('purchase_request_line', sa.Column('purchase_request', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('financial_asset_number', sa.String(length=255), nullable=True))
    op.add_column('purchase_request_line', sa.Column('row_no', sa.Integer(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('item', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('item_name', sa.String(length=255), nullable=True))
    op.add_column('purchase_request_line', sa.Column('item_description', sa.Text(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('unit_of_measure', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('site', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('account_code', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('cost_code', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('vendor', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('po_num', sa.String(length=255), nullable=True))
    op.add_column('purchase_request_line', sa.Column('date_required', sa.DateTime(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('qty_required', sa.Integer(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('qty_received', sa.Integer(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('total_line_amount', sa.Float(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('unit_cost', sa.Float(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('base_currency', sa.String(length=50), nullable=True))
    op.add_column('purchase_request_line', sa.Column('base_currency_unit', sa.Float(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('base_currency_line_amount', sa.Float(), nullable=True))
    op.add_column('purchase_request_line', sa.Column('conversion_factor', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'purchase_request_line', 'purchase_request', ['purchase_request'], ['id'])
    op.create_foreign_key(None, 'purchase_request_line', 'currency', ['base_currency'], ['id'])
    op.create_foreign_key(None, 'purchase_request_line', 'unit_of_measure', ['unit_of_measure'], ['id'])
    op.create_foreign_key(None, 'purchase_request_line', 'site', ['site'], ['id'])
    op.create_foreign_key(None, 'purchase_request_line', 'department', ['department'], ['id'])
    op.create_foreign_key(None, 'purchase_request_line', 'account', ['account_code'], ['id'])
    op.create_foreign_key(None, 'purchase_request_line', 'cost_code', ['cost_code'], ['id'])
    op.create_foreign_key(None, 'purchase_request_line', 'vendor', ['vendor'], ['id'])
    op.create_foreign_key(None, 'purchase_request_line', 'item', ['item'], ['id'])
    op.drop_column('purchase_request_line', 'quantity')
    op.drop_column('purchase_request_line', 'description')
    op.alter_column('putaway', 'putaway_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('reason_code', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('reason_code', 'movement_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('reason_code', 'approval_threshold',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('request_activity_type', 'menu',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('request_activity_type', 'type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('request_activity_type', 'state',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('request_activity_type', 'role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sensor', 'uom_short_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('sensor', 'property_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('sensor', 'collection_frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('sensor_data', 'timestamp',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('site', 'site_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('stock_count', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('stock_count', 'method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('stock_count', 'basis',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('stock_count', 'abc_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('stock_count', 'freeze_policy',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('stock_ledger_entry', 'voucher_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('stock_ledger_entry', 'voucher_no',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'system', 'site', ['site'], ['id'])
    op.alter_column('transfer', 'transfer_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('unit_of_measure', 'short_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('work_order', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order', 'work_order_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_order', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_order', 'severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_order_activity', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_activity', 'work_item_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_order_checklist', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_order_checklist_detail', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_order_equipment', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_equipment_actual_hours', 'hour',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_equipment_assignment', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_equipment_assignment', 'asset_class_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_labor', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_labor_actual_hours', 'time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_labor_assignment', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_labor_assignment', 'trade_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_parts', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_parts_reservation', 'item_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_order_parts_reservation', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_schedule_details', 'day',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_schedule_details', 'start_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('work_schedule_details', 'end_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('workflow_state_links', 'is_initial',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('workflow_state_links', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workflow_transitions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workflows', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workflow_transitions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workflow_state_links', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workflow_state_links', 'is_initial',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('work_schedule_details', 'end_time',
               existing_type=sa.String(length=255),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('work_schedule_details', 'start_time',
               existing_type=sa.String(length=255),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('work_schedule_details', 'day',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('work_order_parts_reservation', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_parts_reservation', 'item_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_parts', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_labor_assignment', 'trade_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_labor_assignment', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_labor_actual_hours', 'time',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_labor', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_equipment_assignment', 'asset_class_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_equipment_assignment', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_equipment_actual_hours', 'hour',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_equipment', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_checklist_detail', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_checklist', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_activity', 'work_item_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order_activity', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order', 'severity',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order', 'priority',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order', 'work_order_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_order', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('unit_of_measure', 'short_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('transfer', 'transfer_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'system', type_='foreignkey')
    op.alter_column('stock_ledger_entry', 'voucher_no',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('stock_ledger_entry', 'voucher_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('stock_count', 'freeze_policy',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('stock_count', 'abc_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('stock_count', 'basis',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('stock_count', 'method',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('stock_count', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('site', 'site_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('sensor_data', 'timestamp',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('sensor', 'collection_frequency',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('sensor', 'property_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('sensor', 'uom_short_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('request_activity_type', 'role',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('request_activity_type', 'state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('request_activity_type', 'type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('request_activity_type', 'menu',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('reason_code', 'approval_threshold',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('reason_code', 'movement_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('reason_code', 'code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('putaway', 'putaway_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('purchase_request_line', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('purchase_request_line', sa.Column('quantity', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_constraint(None, 'purchase_request_line', type_='foreignkey')
    op.drop_column('purchase_request_line', 'conversion_factor')
    op.drop_column('purchase_request_line', 'base_currency_line_amount')
    op.drop_column('purchase_request_line', 'base_currency_unit')
    op.drop_column('purchase_request_line', 'base_currency')
    op.drop_column('purchase_request_line', 'unit_cost')
    op.drop_column('purchase_request_line', 'total_line_amount')
    op.drop_column('purchase_request_line', 'qty_received')
    op.drop_column('purchase_request_line', 'qty_required')
    op.drop_column('purchase_request_line', 'date_required')
    op.drop_column('purchase_request_line', 'po_num')
    op.drop_column('purchase_request_line', 'vendor')
    op.drop_column('purchase_request_line', 'cost_code')
    op.drop_column('purchase_request_line', 'account_code')
    op.drop_column('purchase_request_line', 'department')
    op.drop_column('purchase_request_line', 'site')
    op.drop_column('purchase_request_line', 'unit_of_measure')
    op.drop_column('purchase_request_line', 'item_description')
    op.drop_column('purchase_request_line', 'item_name')
    op.drop_column('purchase_request_line', 'item')
    op.drop_column('purchase_request_line', 'row_no')
    op.drop_column('purchase_request_line', 'financial_asset_number')
    op.drop_column('purchase_request_line', 'purchase_request')
    op.drop_column('purchase_request_line', 'workflow_state')
    op.alter_column('purchase_request', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('position_relation', 'position_b_description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('position_relation', 'position_a_description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_constraint(None, 'position', type_='foreignkey')
    op.alter_column('position', 'attach_img',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('position', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('planned_maintenance_activity', 'maintenance_schedule',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('organization', 'organizational_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('maintenance_request', 'priority',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('maintenance_request', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('maintenance_order_detail', 'resource_availability_status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('maintenance_order_detail', 'due_date',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('maintenance_condition', 'comparison_operator',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('maintenance_condition', 'property_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('maintenance_condition', 'uom_short_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('maintenance_calendar', 'frequency',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.alter_column('location', 'address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('labor_availability_details', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('labor_availability_details', 'hour',
               existing_type=sa.String(length=255),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.drop_constraint(None, 'labor', type_='foreignkey')
    op.alter_column('labor', 'pr_line_no',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('labor', 'labor_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('item_return', 'return_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('item_return', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('item_issue', 'issue_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('item_issue', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('item_class', 'valuation_method',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('item_class', 'item_class_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('inventory_adjustment', 'reference_doctype',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('inventory_adjustment', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'incident_employee', type_='foreignkey')
    op.alter_column('incident_employee', 'injury_severity',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('incident_employee', 'role_in_incident',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.alter_column('incident', 'severity',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.alter_column('equipment', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('equipment', 'equipment_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('entity_permissions', 'in_sidebar',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('entity_permissions', 'can_delete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('entity_permissions', 'can_update',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('entity_permissions', 'can_create',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('entity_permissions', 'can_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'employee_site', type_='foreignkey')
    op.drop_constraint(None, 'employee_site', type_='foreignkey')
    op.drop_constraint(None, 'employee_site', type_='foreignkey')
    op.drop_constraint(None, 'disposed', type_='foreignkey')
    op.alter_column('disposed', 'disposal_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('disposed', 'disposal_method',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('disposed', 'condition',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('department', 'overhead_method',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('department', 'department_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('currency', 'symbol',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint(None, 'cost_code', type_='foreignkey')
    op.alter_column('cost_code', 'scope',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('cost_code', 'code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('checklist', 'checklist_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('breakdown', 'end_time',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('breakdown', 'start_time',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('asset_property', 'uom_short_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('asset_class_property', 'uom_short_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('asset_class', 'class_icon',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('asset', sa.Column('manufacturer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('asset_class_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.alter_column('asset', 'asset_tag',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('asset', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('account', 'account_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('account', 'account_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_table('project',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('project_created_by_fkey')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('project_manager_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_pkey'))
    )
    op.create_table('todo',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todo_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('todo_comment',
    sa.Column('todo_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], name=op.f('todo_comment_todo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('todo_comment_pkey'))
    )
    # ### end Alembic commands ###
