"""asset class icon upload and diagram filters

Revision ID: 17aab2f5faeb
Revises: 7478b2689c59
Create Date: 2026-03-06 04:47:39.681390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17aab2f5faeb'
down_revision: Union[str, None] = '7478b2689c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_class', sa.Column('class_icon', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_class', 'class_icon')
    # ### end Alembic commands ###
