"""auto migration

Revision ID: 3a2f18bfc772
Revises: c4d9e2a1b7f0
Create Date: 2026-02-18 11:43:09.403319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a2f18bfc772'
down_revision: Union[str, None] = 'c4d9e2a1b7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Minimal migration: add source_stock_count to inventory_adjustment for audit traceability
    op.add_column('inventory_adjustment', sa.Column('source_stock_count', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'inventory_adjustment', 'stock_count', ['source_stock_count'], ['id'])


def downgrade() -> None:
    op.drop_constraint(None, 'inventory_adjustment', type_='foreignkey')
    op.drop_column('inventory_adjustment', 'source_stock_count')


def _old_autogenerated_downgrade_unused() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfq_log')
    op.drop_table('RfqLine')
    op.drop_index(op.f('idx_asset_name'), table_name='asset')
    op.drop_index(op.f('idx_asset_site'), table_name='asset')
    op.create_unique_constraint(None, 'asset', ['asset_tag'])
    op.drop_constraint(op.f('asset_manufacturer_fkey'), 'asset', type_='foreignkey')
    op.create_foreign_key(None, 'asset', 'inventory', ['inventory'], ['id'])
    op.create_foreign_key(None, 'asset', 'employee', ['assigned_to'], ['id'])
    op.drop_column('asset', 'asset_name')
    op.drop_column('asset', 'position_name')
    op.drop_column('asset', 'manufacturer')
    op.drop_column('asset', 'assigned_to_name')
    op.drop_column('asset', 'purchase_date')
    op.drop_column('asset', 'location_name')
    op.drop_column('asset', 'site_name')
    op.drop_column('asset', 'system_name')
    op.drop_column('asset', 'purchase_cost')
    op.drop_column('asset', 'asset_class_name')
    op.drop_column('asset', 'department_name')
    op.drop_column('asset_class', 'class_icon')
    op.drop_column('asset_class', 'manual')
    op.create_foreign_key(None, 'department', 'employee', ['department_manager'], ['id'])
    op.create_foreign_key(None, 'employee', 'users', ['user'], ['id'])
    op.create_unique_constraint('uq_entity_name', 'entity_orders', ['entity_name'])
    op.create_foreign_key(None, 'equipment', 'inventory', ['inventory'], ['id'])
    op.create_foreign_key(None, 'equipment', 'employee', ['custodian'], ['id'])
    op.create_foreign_key(None, 'incident', 'employee', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'incident_employee', 'employee', ['employee'], ['id'])
    op.create_foreign_key(None, 'inspection', 'employee', ['inspector'], ['id'])
    op.create_foreign_key(None, 'inspection', 'inventory', ['inventory'], ['id'])
    op.add_column('inventory_adjustment', sa.Column('source_stock_count', sa.String(length=50), nullable=True))
    op.alter_column('inventory_adjustment', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'inventory_adjustment', 'stock_count', ['source_stock_count'], ['id'])
    op.create_foreign_key(None, 'inventory_adjustment_line', 'inventory', ['inventory'], ['id'])
    op.drop_column('item', 'manufacturer')
    op.drop_column('item', 'category')
    op.drop_column('item', 'name')
    op.drop_column('item', 'model')
    op.drop_column('item', 'lead_time_days')
    op.drop_column('item', 'min_stock_level')
    op.drop_column('item', 'vendor')
    op.drop_column('item', 'price')
    op.drop_column('item', 'max_stock_level')
    op.alter_column('item_issue', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'item_issue', 'employee', ['issue_to'], ['id'])
    op.create_foreign_key(None, 'item_issue_line', 'inventory', ['inventory'], ['id'])
    op.alter_column('item_return', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'item_return', 'employee', ['returned_by'], ['id'])
    op.create_foreign_key(None, 'labor', 'employee', ['employee'], ['id'])
    op.drop_column('location', 'location_name')
    op.create_foreign_key(None, 'maintenance_request', 'employee', ['requestor'], ['id'])
    op.create_unique_constraint('uq_module_name', 'module_orders', ['module_name'])
    op.alter_column('purchase_order', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_order', 'source_rfq',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('purchase_order', 'site',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('purchase_order', 'department',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_purchase_order_date_ordered'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_vendor'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_workflow_state'), table_name='purchase_order')
    op.alter_column('purchase_order_line', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_order_line', 'po_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('purchase_order_line', 'site',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('purchase_order_line', 'department',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_purchase_order_line_item_id'), table_name='purchase_order_line')
    op.drop_index(op.f('ix_purchase_order_line_po_id'), table_name='purchase_order_line')
    op.drop_index(op.f('ix_purchase_order_line_workflow_state'), table_name='purchase_order_line')
    op.create_foreign_key(None, 'purchase_receipt', 'purchase_order_line', ['purchase_order_line'], ['id'])
    op.create_foreign_key(None, 'purchase_receipt', 'cost_code', ['cost_code'], ['id'])
    op.drop_column('purchase_receipt', 'workflow_state')
    op.drop_column('purchase_receipt', 'attachments')
    op.alter_column('purchase_request', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'purchase_request', 'employee', ['requestor'], ['id'])
    op.drop_column('purchase_request', 'total_amount')
    op.drop_column('purchase_request', 'request_date')
    op.drop_column('purchase_request', 'status')
    op.drop_column('purchase_request', 'required_date')
    op.drop_column('purchase_request', 'vendor')
    op.alter_column('purchase_request_line', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'purchase_return', 'inventory', ['inventory'], ['id'])
    op.alter_column('request_for_quotation', 'workflow_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_constraint(op.f('fk_rfq_purchase_request'), 'request_for_quotation', type_='foreignkey')
    op.drop_constraint(op.f('fk_rfq_generated_by'), 'request_for_quotation', type_='foreignkey')
    op.drop_constraint(op.f('fk_rfq_awarded_vendor'), 'request_for_quotation', type_='foreignkey')
    op.create_foreign_key(None, 'request_for_quotation', 'purchase_request', ['purchase_request'], ['id'])
    op.create_foreign_key(None, 'request_for_quotation', 'vendor', ['awarded_vendor'], ['id'])
    op.create_foreign_key(None, 'request_for_quotation', 'employee', ['generated_by'], ['id'])
    op.create_unique_constraint(None, 'roles', ['name'])
    op.alter_column('service_request', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('service_request', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('service_request', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('service_request', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_foreign_key(None, 'site', 'employee', ['site_manager'], ['id'])
    op.alter_column('stock_count', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('stock_count', 'attach_csv')
    op.create_foreign_key(None, 'stock_count_line', 'inventory', ['inventory'], ['id'])
    op.drop_column('system', 'site_name')
    op.drop_column('system', 'location_name')
    op.drop_column('system', 'parent_system_name')
    op.drop_column('system', 'system_name')
    op.create_foreign_key(None, 'transfer', 'inventory', ['inventory'], ['id'])
    op.create_foreign_key(None, 'transfer', 'employee', ['moved_by'], ['id'])
    op.create_foreign_key(None, 'transfer_receipt', 'inventory', ['inventory'], ['id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_foreign_key(None, 'work_order_checklist', 'employee', ['inspector_id'], ['id'])
    op.create_foreign_key(None, 'work_order_parts_reservation', 'inventory', ['inventory'], ['id'])
    op.create_unique_constraint(None, 'workflow_actions', ['slug'])
    op.create_index('ix_workflow_state_links_workflow', 'workflow_state_links', ['workflow_id'], unique=False)
    op.create_unique_constraint('uq_workflow_state', 'workflow_state_links', ['workflow_id', 'state_id'])
    op.drop_constraint(op.f('workflow_state_links_state_id_fkey'), 'workflow_state_links', type_='foreignkey')
    op.drop_constraint(op.f('workflow_state_links_workflow_id_fkey'), 'workflow_state_links', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_state_links', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_state_links', 'workflow_states', ['state_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(None, 'workflow_states', ['slug'])
    op.create_index('ix_workflow_transitions_workflow', 'workflow_transitions', ['workflow_id'], unique=False)
    op.drop_constraint(op.f('workflow_transitions_workflow_id_fkey'), 'workflow_transitions', type_='foreignkey')
    op.drop_constraint(op.f('workflow_transitions_action_id_fkey'), 'workflow_transitions', type_='foreignkey')
    op.drop_constraint(op.f('workflow_transitions_to_state_id_fkey'), 'workflow_transitions', type_='foreignkey')
    op.drop_constraint(op.f('workflow_transitions_from_state_id_fkey'), 'workflow_transitions', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_transitions', 'workflow_states', ['from_state_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'workflow_transitions', 'workflow_actions', ['action_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'workflow_transitions', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_transitions', 'workflow_states', ['to_state_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(None, 'workflows', ['target_entity'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='unique')
    op.drop_constraint(None, 'workflow_transitions', type_='foreignkey')
    op.drop_constraint(None, 'workflow_transitions', type_='foreignkey')
    op.drop_constraint(None, 'workflow_transitions', type_='foreignkey')
    op.drop_constraint(None, 'workflow_transitions', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_transitions_from_state_id_fkey'), 'workflow_transitions', 'workflow_states', ['from_state_id'], ['id'])
    op.create_foreign_key(op.f('workflow_transitions_to_state_id_fkey'), 'workflow_transitions', 'workflow_states', ['to_state_id'], ['id'])
    op.create_foreign_key(op.f('workflow_transitions_action_id_fkey'), 'workflow_transitions', 'workflow_actions', ['action_id'], ['id'])
    op.create_foreign_key(op.f('workflow_transitions_workflow_id_fkey'), 'workflow_transitions', 'workflows', ['workflow_id'], ['id'])
    op.drop_index('ix_workflow_transitions_workflow', table_name='workflow_transitions')
    op.drop_constraint(None, 'workflow_states', type_='unique')
    op.drop_constraint(None, 'workflow_state_links', type_='foreignkey')
    op.drop_constraint(None, 'workflow_state_links', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_state_links_workflow_id_fkey'), 'workflow_state_links', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(op.f('workflow_state_links_state_id_fkey'), 'workflow_state_links', 'workflow_states', ['state_id'], ['id'])
    op.drop_constraint('uq_workflow_state', 'workflow_state_links', type_='unique')
    op.drop_index('ix_workflow_state_links_workflow', table_name='workflow_state_links')
    op.drop_constraint(None, 'workflow_actions', type_='unique')
    op.drop_constraint(None, 'work_order_parts_reservation', type_='foreignkey')
    op.drop_constraint(None, 'work_order_checklist', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transfer_receipt', type_='foreignkey')
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.add_column('system', sa.Column('system_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('system', sa.Column('parent_system_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('system', sa.Column('location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('system', sa.Column('site_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock_count_line', type_='foreignkey')
    op.add_column('stock_count', sa.Column('attach_csv', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('stock_count', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.alter_column('service_request', 'priority',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('service_request', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('service_request', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('service_request', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'request_for_quotation', type_='foreignkey')
    op.drop_constraint(None, 'request_for_quotation', type_='foreignkey')
    op.drop_constraint(None, 'request_for_quotation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rfq_awarded_vendor'), 'request_for_quotation', 'vendor', ['awarded_vendor'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_rfq_generated_by'), 'request_for_quotation', 'employee', ['generated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_rfq_purchase_request'), 'request_for_quotation', 'purchase_request', ['purchase_request'], ['id'], ondelete='SET NULL')
    op.alter_column('request_for_quotation', 'workflow_state',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_constraint(None, 'purchase_return', type_='foreignkey')
    op.alter_column('purchase_request_line', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('purchase_request', sa.Column('vendor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('purchase_request', sa.Column('required_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('purchase_request', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('purchase_request', sa.Column('request_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('purchase_request', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase_request', type_='foreignkey')
    op.alter_column('purchase_request', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('purchase_receipt', sa.Column('attachments', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('purchase_receipt', sa.Column('workflow_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase_receipt', type_='foreignkey')
    op.drop_constraint(None, 'purchase_receipt', type_='foreignkey')
    op.create_index(op.f('ix_purchase_order_line_workflow_state'), 'purchase_order_line', ['workflow_state'], unique=False)
    op.create_index(op.f('ix_purchase_order_line_po_id'), 'purchase_order_line', ['po_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_line_item_id'), 'purchase_order_line', ['item_id'], unique=False)
    op.alter_column('purchase_order_line', 'department',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('purchase_order_line', 'site',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('purchase_order_line', 'po_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('purchase_order_line', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_purchase_order_workflow_state'), 'purchase_order', ['workflow_state'], unique=False)
    op.create_index(op.f('ix_purchase_order_vendor'), 'purchase_order', ['vendor'], unique=False)
    op.create_index(op.f('ix_purchase_order_date_ordered'), 'purchase_order', ['date_ordered'], unique=False)
    op.alter_column('purchase_order', 'department',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('purchase_order', 'site',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('purchase_order', 'source_rfq',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('purchase_order', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('uq_module_name', 'module_orders', type_='unique')
    op.drop_constraint(None, 'maintenance_request', type_='foreignkey')
    op.add_column('location', sa.Column('location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'labor', type_='foreignkey')
    op.drop_constraint(None, 'item_return', type_='foreignkey')
    op.alter_column('item_return', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'item_issue_line', type_='foreignkey')
    op.drop_constraint(None, 'item_issue', type_='foreignkey')
    op.alter_column('item_issue', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('item', sa.Column('max_stock_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('vendor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('min_stock_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('lead_time_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('manufacturer', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory_adjustment_line', type_='foreignkey')
    op.drop_constraint(None, 'inventory_adjustment', type_='foreignkey')
    op.alter_column('inventory_adjustment', 'workflow_state',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('inventory_adjustment', 'source_stock_count')
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.drop_constraint(None, 'incident_employee', type_='foreignkey')
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint('uq_entity_name', 'entity_orders', type_='unique')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.add_column('asset_class', sa.Column('manual', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('asset_class', sa.Column('class_icon', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('department_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('asset_class_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('purchase_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('system_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('site_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('assigned_to_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('manufacturer', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('position_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('asset_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.create_foreign_key(op.f('asset_manufacturer_fkey'), 'asset', 'manufacturer', ['manufacturer'], ['id'])
    op.drop_constraint(None, 'asset', type_='unique')
    op.create_index(op.f('idx_asset_site'), 'asset', ['site'], unique=False)
    op.create_index(op.f('idx_asset_name'), 'asset', ['asset_name'], unique=False)
    op.create_table('RfqLine',
    sa.Column('rfq_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pr_line', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('item', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('item_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('RfqLine_pkey'))
    )
    op.create_table('rfq_log',
    sa.Column('purchase_request', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_issue', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('requestor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['employee.id'], name=op.f('rfq_log_generated_by_fkey')),
    sa.ForeignKeyConstraint(['purchase_request'], ['purchase_request.id'], name=op.f('rfq_log_purchase_request_fkey')),
    sa.ForeignKeyConstraint(['requestor'], ['employee.id'], name=op.f('rfq_log_requestor_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rfq_log_pkey'))
    )
    # ### end Alembic commands ###
