"""Nullable error_log fields

Revision ID: 3bc155a5530e
Revises: fc5c196cb58c
Create Date: 2026-02-27 23:28:52.327868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc155a5530e'
down_revision: Union[str, None] = 'fc5c196cb58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('error_log', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('error_log', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('error_log', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('error_log', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('error_log', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('error_log', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
