"""add_email_log_and_scheduled_job_log

Revision ID: 6571f4dfd939
Revises: 471b4e4986e2
Create Date: 2026-03-11 13:07:24.770584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6571f4dfd939'
down_revision: Union[str, None] = '471b4e4986e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
