"""add_user_profile_fields

Revision ID: 7478b2689c59
Revises: c54fd46050ae
Create Date: 2026-03-06 03:34:22.377211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7478b2689c59'
down_revision: Union[str, None] = 'c54fd46050ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('contact_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('site', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'site')
    op.drop_column('users', 'department')
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
