"""Add manager to project

Revision ID: 8c6bb258c4c1
Revises: 002_workflow
Create Date: 2026-01-22 09:23:23.856959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6bb258c4c1'
down_revision: Union[str, None] = '002_workflow'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'priority',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('todo', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('todo_comment_todo_id_fkey'), 'todo_comment', type_='foreignkey')
    op.create_foreign_key(None, 'todo_comment', 'todo', ['todo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_comment', type_='foreignkey')
    op.create_foreign_key(op.f('todo_comment_todo_id_fkey'), 'todo_comment', 'todo', ['todo_id'], ['id'])
    op.alter_column('todo', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('todo', 'priority',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
