"""Add error_log table

Revision ID: a6366382fd5f
Revises: 42796335f308
Create Date: 2026-02-27 22:56:36.400925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6366382fd5f'
down_revision: Union[str, None] = '42796335f308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_log',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('RfqLine')
    op.drop_column('purchase_request_line', 'item_name')
    op.drop_column('sales_order_item', 'row_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_item', sa.Column('row_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_request_line', sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('RfqLine',
    sa.Column('rfq_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pr_line', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('item', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('item_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('RfqLine_pkey'))
    )
    op.drop_table('error_log')
    # ### end Alembic commands ###
