"""Add missing fields to RFQ

Revision ID: add_missing_rfq_fields
Revises: 6d1c2f8e9a0b
Create Date: 2026-02-06 21:37:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_missing_rfq_fields'
down_revision: Union[str, None] = '6d1c2f8e9a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_for_quotation', sa.Column('purchase_request', sa.String(length=50), nullable=True))
    op.add_column('request_for_quotation', sa.Column('generated_by', sa.String(length=50), nullable=True))
    op.add_column('request_for_quotation', sa.Column('awarded_vendor', sa.String(length=50), nullable=True))
    op.add_column('request_for_quotation', sa.Column('terms_and_conditions', sa.Text(), nullable=True))
    
    # Update date columns from varchar to date type
    op.execute('ALTER TABLE request_for_quotation ALTER COLUMN date_issue TYPE date USING date_issue::date')
    op.execute('ALTER TABLE request_for_quotation ALTER COLUMN due_date TYPE date USING due_date::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert date columns back to varchar
    op.execute('ALTER TABLE request_for_quotation ALTER COLUMN date_issue TYPE varchar(255)')
    op.execute('ALTER TABLE request_for_quotation ALTER COLUMN due_date TYPE varchar(255)')
    
    op.drop_column('request_for_quotation', 'terms_and_conditions')
    op.drop_column('request_for_quotation', 'awarded_vendor')
    op.drop_column('request_for_quotation', 'generated_by')
    op.drop_column('request_for_quotation', 'purchase_request')
    # ### end Alembic commands ###
