"""fix_user_foreign_key_references

Revision ID: aef1068f18bd
Revises: 016db90c80a2
Create Date: 2026-02-04 12:47:31.350389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef1068f18bd'
down_revision: Union[str, None] = '016db90c80a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'transaction_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('inventory_workflow_state_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_bin_location_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_item_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_asset_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_store_location_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_location_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_site_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_unit_of_measure_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_zone_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_assigned_to_fkey'), 'inventory', type_='foreignkey')
    op.alter_column('item', 'item_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('item', 'abc_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('item_inventory_adjustment_account_fkey'), 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'inventory_adjustment', ['inventory_adjustment_account'], ['id'])
    op.drop_column('item', 'item_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_img', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(op.f('item_inventory_adjustment_account_fkey'), 'item', 'account', ['inventory_adjustment_account'], ['id'])
    op.alter_column('item', 'abc_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('item', 'item_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_foreign_key(op.f('inventory_assigned_to_fkey'), 'inventory', 'employee', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('inventory_zone_fkey'), 'inventory', 'zone', ['zone'], ['id'])
    op.create_foreign_key(op.f('inventory_unit_of_measure_fkey'), 'inventory', 'unit_of_measure', ['unit_of_measure'], ['id'])
    op.create_foreign_key(op.f('inventory_site_fkey'), 'inventory', 'site', ['site'], ['id'])
    op.create_foreign_key(op.f('inventory_location_fkey'), 'inventory', 'location', ['location'], ['id'])
    op.create_foreign_key(op.f('inventory_store_location_fkey'), 'inventory', 'store', ['store_location'], ['id'])
    op.create_foreign_key(op.f('inventory_asset_fkey'), 'inventory', 'asset', ['asset'], ['id'])
    op.create_foreign_key(op.f('inventory_item_fkey'), 'inventory', 'item', ['item'], ['id'])
    op.create_foreign_key(op.f('inventory_bin_location_fkey'), 'inventory', 'bin', ['bin_location'], ['id'])
    op.create_foreign_key(op.f('inventory_workflow_state_fkey'), 'inventory', 'workflow_states', ['workflow_state'], ['id'])
    op.alter_column('inventory', 'transaction_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
