"""Remove redundant fields from asset management entities

Revision ID: b9556313161c
Revises: 532e7889b6c1
Create Date: 2026-02-26 08:47:47.475723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9556313161c'
down_revision: Union[str, None] = '532e7889b6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_class_property', 'uom_short_name')
    op.drop_column('asset_class_property', 'property_name')
    op.drop_column('asset_class_property', 'asset_class_name')
    op.drop_column('asset_position', 'asset_name')
    op.drop_column('asset_position', 'position_name')
    op.drop_column('asset_property', 'uom_short_name')
    op.drop_column('asset_property', 'property_name')
    op.drop_column('asset_property', 'asset_name')
    op.drop_column('property', 'unit_of_measure_name')
    op.drop_column('property', 'property_type_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('property_type_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('unit_of_measure_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset_property', sa.Column('asset_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('asset_property', sa.Column('property_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset_property', sa.Column('uom_short_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset_position', sa.Column('position_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset_position', sa.Column('asset_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('asset_class_property', sa.Column('asset_class_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset_class_property', sa.Column('property_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('asset_class_property', sa.Column('uom_short_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
