"""sync_5807

Revision ID: c54fd46050ae
Revises: 3bc155a5530e
Create Date: 2026-02-28 02:00:52.187147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54fd46050ae'
down_revision: Union[str, None] = '3bc155a5530e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RfqLine',
    sa.Column('rfq_id', sa.String(length=255), nullable=True),
    sa.Column('pr_line', sa.String(length=255), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=True),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('asset', 'manual')
    op.drop_column('employee', 'attachments')
    op.drop_column('reason_code', 'attachments')
    op.add_column('sales_order_item', sa.Column('row_no', sa.Integer(), nullable=True))
    op.alter_column('sales_order_item', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('sales_order_item', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('work_order_activity_activity_type_fkey'), 'work_order_activity', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('work_order_activity_activity_type_fkey'), 'work_order_activity', 'request_activity_type', ['activity_type'], ['id'])
    op.alter_column('sales_order_item', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('sales_order_item', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('sales_order_item', 'row_no')
    op.add_column('reason_code', sa.Column('attachments', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('attachments', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('manual', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('RfqLine')
    # ### end Alembic commands ###
