"""Update error_log fields

Revision ID: fc5c196cb58c
Revises: a6366382fd5f
Create Date: 2026-02-27 23:11:42.807783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5c196cb58c'
down_revision: Union[str, None] = 'a6366382fd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_log', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('error_log', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('error_log', sa.Column('message', sa.Text(), nullable=False))
    op.drop_column('error_log', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_log', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('error_log', 'message')
    op.drop_column('error_log', 'title')
    op.drop_column('error_log', 'status')
    # ### end Alembic commands ###
